<a href="https://colab.research.google.com/github/ananthavarshinireddy123-ai/Varshini-Reddy/blob/main/Datacleaning_processessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data={
    "Name": ["chinni","chikki","varshini","teju",None,"anu"],
    "Age": [22,28, np.nan,21,30,25],
    "City": ["Hyd","Delhi","hyd","delhi","Delhi","Hyd"]
}

df=pd.DataFrame(data)
df

       Name   Age   City
0    chinni  22.0    Hyd
1    chikki  28.0  Delhi
2  varshini   NaN    hyd
3      teju  21.0  delhi
4      None  30.0  Delhi
5       anu  25.0    Hyd

In [22]:
# First few rows
print(df.head())

# Data info
print(df.info())

# Summary statistics
print(df.describe())

                 SUBDIVISION  YEAR   JAN    FEB   MAR    APR    MAY    JUN  \
0  ANDAMAN & NICOBAR ISLANDS  1901  49.2   87.1  29.2    2.3  528.8  517.5
1  ANDAMAN & NICOBAR ISLANDS  1902   0.0  159.8  12.2    0.0  446.1  537.1
2  ANDAMAN & NICOBAR ISLANDS  1903  12.7  144.0   0.0    1.0  235.1  479.9
3  ANDAMAN & NICOBAR ISLANDS  1904   9.4   14.7   0.0  202.4  304.5  495.1
4  ANDAMAN & NICOBAR ISLANDS  1905   1.3    0.0   3.3   26.9  279.5  628.7

     JUL    AUG    SEP    OCT    NOV    DEC  ANNUAL  Jan-Feb  Mar-May  \
0  365.1  481.1  332.6  388.5  558.2   33.6  3373.2    136.3    560.3
1  228.9  753.7  666.2  197.2  359.0  160.5  3520.7    159.8    458.3
2  728.4  326.7  339.0  181.2  284.4  225.0  2957.4    156.7    236.1
3  502.0  160.1  820.4  222.2  308.7   40.1  3079.6     24.1    506.9
4  368.7  330.5  297.0  260.7   25.4  344.7  2566.7      1.3    309.7

   Jun-Sep  Oct-Dec
0   1696.3    980.3
1   2185.9    716.7
2   1874.0    690.6
3   1977.6    571.0
4   1624.9    630.8
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4116 entries, 0 to 4115
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SUBDIVISION  4116 non-null   object
 1   YEAR         4116 non-null   int64
 2   JAN          4116 non-null   float64
 3   FEB          4116 non-null   float64
 4   MAR          4116 non-null   float64
 5   APR          4116 non-null   float64
 6   MAY          4116 non-null   float64
 7   JUN          4116 non-null   float64
 8   JUL          4116 non-null   float64
 9   AUG          4116 non-null   float64
 10  SEP          4116 non-null   float64
 11  OCT          4116 non-null   float64
 12  NOV          4116 non-null   float64
 13  DEC          4116 non-null   float64
 14  ANNUAL       4116 non-null   float64
 15  Jan-Feb      4116 non-null   float64
 16  Mar-May      4116 non-null   float64
 17  Jun-Sep      4116 non-null   float64
 18  Oct-Dec      4116 non-null   float64
dtypes: float64(17), int64(1), object(1)
memory usage: 611.1+ KB
None
              YEAR          JAN          FEB          MAR          APR  \
count  4116.000000  4116.000000  4116.000000  4116.000000  4116.000000
mean   1958.218659    18.957320    21.805325    27.359197    43.127432
std      33.140898    33.569044    35.896396    46.925176    67.798192
min    1901.000000     0.000000     0.000000     0.000000     0.000000
25%    1930.000000     0.600000     0.600000     1.000000     3.000000
50%    1958.000000     6.000000     6.700000     7.900000    15.700000
75%    1987.000000    22.125000    26.800000    31.225000    49.825000
max    2015.000000   583.700000   403.500000   605.600000   595.100000

               MAY          JUN          JUL          AUG          SEP  \
count  4116.000000  4116.000000  4116.000000  4116.000000  4116.000000
mean     85.745417   230.234444   347.214334   290.263497   197.361922
std     123.189974   234.568120   269.310313   188.678707   135.309591
min       0.000000     0.400000     0.000000     0.000000     0.100000
25%       8.600000    70.475000   175.900000   156.150000   100.600000
50%      36.700000   138.900000   284.900000   259.500000   174.100000
75%      96.825000   304.950000   418.225000   377.725000   265.725000
max    1168.600000  1609.900000  2362.800000  1664.600000  1222.000000

               OCT          NOV          DEC       ANNUAL      Jan-Feb  \
count  4116.000000  4116.000000  4116.000000  4116.000000  4116.000000
mean     95.507009    39.866163    18.870580  1411.008900    40.747786
std      99.434452    68.593545    42.318098   900.986632    59.265023
min       0.000000     0.000000     0.000000    62.300000     0.000000
25%      14.600000     0.700000     0.100000   806.450000     4.100000
50%      65.750000     9.700000     3.100000  1125.450000    19.300000
75%     148.300000    45.825000    17.700000  1635.100000    50.300000
max     948.300000   648.900000   617.500000  6331.100000   699.500000

           Mar-May      Jun-Sep      Oct-Dec
count  4116.000000  4116.000000  4116.000000
mean    155.901753  1064.724769   154.100487
std     201.096692   706.881054   166.678751
min       0.000000    57.400000     0.000000
25%      24.200000   574.375000    34.200000
50%      75.200000   882.250000    98.800000
75%     196.900000  1287.550000   212.600000
max    1745.800000  4536.900000  1252.500000

In [ ]:
# Check missing values
print(df.isnull())

# Count missing values
df.isnull().sum() #count of missing values

    Name    Age   City
0  False  False  False
1  False  False  False
2  False   True  False
3  False  False  False
4   True  False  False
5  False  False  False

Name    1
Age     1
City    0
dtype: int64

In [ ]:
# Drop rows with missing values
df_drop = df.dropna()
df_drop

     Name   Age   City
0  chinni  22.0    Hyd
1  chikki  28.0  Delhi
3    teju  21.0  delhi
5     anu  25.0    Hyd

In [ ]:
#  FIling Missing Values

df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Name"] = df["Name"].fillna(df["Name"].mode()[0])

df

       Name   Age   City
0    chinni  22.0    Hyd
1    chikki  28.0  Delhi
2  varshini  25.2    hyd
3      teju  21.0  delhi
4       anu  30.0  Delhi
5       anu  25.0    Hyd

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Age": [20, np.nan, 25, 30,20],
    "Salary": [20000, 25000, np.nan, 40000,20000],
    "City": ["Mumbai", "Delhi", "Pune", "Mumbai","Mumbai"]
})

df

    Age   Salary    City
0  20.0  20000.0  Mumbai
1   NaN  25000.0   Delhi
2  25.0      NaN    Pune
3  30.0  40000.0  Mumbai
4  20.0  20000.0  Mumbai

In [ ]:
# Fill multiple columns with mean

df[["Age", "Salary"]] = df[["Age", "Salary"]].fillna(df[["Age", "Salary"]].mean())

df

     Age   Salary    City
0  20.00  20000.0  Mumbai
1  23.75  25000.0   Delhi
2  25.00  26250.0    Pune
3  30.00  40000.0  Mumbai
4  20.00  20000.0  Mumbai

In [ ]:
# Convert multiple columns to integer

df[["Age", "Salary"]] = df[["Age", "Salary"]].astype(int)

df.dtypes
df

   Age  Salary    City
0   20   20000  Mumbai
1   23   25000   Delhi
2   25   26250    Pune
3   30   40000  Mumbai
4   20   20000  Mumbai

In [ ]:
# Increase values by 10%

df[["Age", "Salary"]] = df[["Age", "Salary"]].apply(lambda x: x * 1.1)

df

    Age   Salary    City
0  22.0  22000.0  Mumbai
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0  Mumbai
4  22.0  22000.0  Mumbai

In [ ]:
# Replace specific values

df[["City"]] = df[["City"]].replace("Mumbai", "MUMBAI")
df

    Age   Salary    City
0  22.0  22000.0  MUMBAI
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0  MUMBAI
4  22.0  22000.0  MUMBAI

In [ ]:
#Encoding
df_encoded=pd.get_dummies(df,columns=["City"])
df_encoded

    Age   Salary  City_Delhi  City_MUMBAI  City_Pune
0  22.0  22000.0       False         True      False
1  25.3  27500.0        True        False      False
2  27.5  28875.0       False        False       True
3  33.0  44000.0       False         True      False
4  22.0  22000.0       False         True      False

In [ ]:
df_no_dup = df.drop_duplicates()
df_no_dup

    Age   Salary    City
0  22.0  22000.0  MUMBAI
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0  MUMBAI

In [ ]:
# Convert all city names to lowercase
df["City"] = df["City"].str.upper()
df2=df.dropna()
df2

    Age   Salary    City
0  22.0  22000.0  MUMBAI
1  25.3  27500.0   DELHI
2  27.5  28875.0    PUNE
3  33.0  44000.0  MUMBAI
4  22.0  22000.0  MUMBAI

In [ ]:
df2.dropna()
df2["Age"] = df2["Age"].astype(int)
print(df2)
df2.drop_duplicates()

   Age   Salary    City
0   22  22000.0  MUMBAI
1   25  27500.0   DELHI
2   27  28875.0    PUNE
3   33  44000.0  MUMBAI
4   22  22000.0  MUMBAI

   Age   Salary    City
0   22  22000.0  MUMBAI
1   25  27500.0   DELHI
2   27  28875.0    PUNE
3   33  44000.0  MUMBAI

In [ ]:
import pandas as pd

df = pd.read_csv("/content/rainfall.csv", encoding='latin1')

# First 5 rows
print(df.head())
# Last 5 rows
print(df.tail())

                 SUBDIVISION  YEAR   JAN    FEB   MAR    APR    MAY    JUN  \
0  ANDAMAN & NICOBAR ISLANDS  1901  49.2   87.1  29.2    2.3  528.8  517.5
1  ANDAMAN & NICOBAR ISLANDS  1902   0.0  159.8  12.2    0.0  446.1  537.1
2  ANDAMAN & NICOBAR ISLANDS  1903  12.7  144.0   0.0    1.0  235.1  479.9
3  ANDAMAN & NICOBAR ISLANDS  1904   9.4   14.7   0.0  202.4  304.5  495.1
4  ANDAMAN & NICOBAR ISLANDS  1905   1.3    0.0   3.3   26.9  279.5  628.7

     JUL    AUG    SEP    OCT    NOV    DEC  ANNUAL  Jan-Feb  Mar-May  \
0  365.1  481.1  332.6  388.5  558.2   33.6  3373.2    136.3    560.3
1  228.9  753.7  666.2  197.2  359.0  160.5  3520.7    159.8    458.3
2  728.4  326.7  339.0  181.2  284.4  225.0  2957.4    156.7    236.1
3  502.0  160.1  820.4  222.2  308.7   40.1  3079.6     24.1    506.9
4  368.7  330.5  297.0  260.7   25.4  344.7  2566.7      1.3    309.7

   Jun-Sep  Oct-Dec
0   1696.3    980.3
1   2185.9    716.7
2   1874.0    690.6
3   1977.6    571.0
4   1624.9    630.8
      SUBDIVISION  YEAR   JAN   FEB   MAR   APR    MAY    JUN    JUL    AUG  \
4111  LAKSHADWEEP  2011   5.1   2.8   3.1  85.9  107.2  153.6  350.2  254.0
4112  LAKSHADWEEP  2012  19.2   0.1   1.6  76.8   21.2  327.0  231.5  381.2
4113  LAKSHADWEEP  2013  26.2  34.4  37.5   5.3   88.3  426.2  296.4  154.4
4114  LAKSHADWEEP  2014  53.2  16.1   4.4  14.9   57.4  244.1  116.1  466.1
4115  LAKSHADWEEP  2015   2.2   0.5   3.7  87.1  133.1  296.6  257.5  146.4

        SEP    OCT    NOV    DEC  ANNUAL  Jan-Feb  Mar-May  Jun-Sep  Oct-Dec
4111  255.2  117.4  184.3   14.9  1533.7      7.9    196.2   1013.0    316.6
4112  179.8  145.9   12.4    8.8  1405.5     19.3     99.6   1119.5    167.1
4113  180.0   72.8   78.1   26.7  1426.3     60.6    131.1   1057.0    177.6
4114  132.2  169.2   59.0   62.3  1395.0     69.3     76.7    958.5    290.5
4115  160.4  165.4  231.0  159.0  1642.9      2.7    223.9    860.9    555.4

In [23]:
df.head()
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4116 entries, 0 to 4115
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SUBDIVISION  4116 non-null   object
 1   YEAR         4116 non-null   int64
 2   JAN          4116 non-null   float64
 3   FEB          4116 non-null   float64
 4   MAR          4116 non-null   float64
 5   APR          4116 non-null   float64
 6   MAY          4116 non-null   float64
 7   JUN          4116 non-null   float64
 8   JUL          4116 non-null   float64
 9   AUG          4116 non-null   float64
 10  SEP          4116 non-null   float64
 11  OCT          4116 non-null   float64
 12  NOV          4116 non-null   float64
 13  DEC          4116 non-null   float64
 14  ANNUAL       4116 non-null   float64
 15  Jan-Feb      4116 non-null   float64
 16  Mar-May      4116 non-null   float64
 17  Jun-Sep      4116 non-null   float64
 18  Oct-Dec      4116 non-null   float64
dtypes: float64(17), int64(1), object(1)
memory usage: 611.1+ KB

SUBDIVISION    0
YEAR           0
JAN            0
FEB            0
MAR            0
APR            0
MAY            0
JUN            0
JUL            0
AUG            0
SEP            0
OCT            0
NOV            0
DEC            0
ANNUAL         0
Jan-Feb        0
Mar-May        0
Jun-Sep        0
Oct-Dec        0
dtype: int64

In [24]:
df["YEAR"] = df["YEAR"].astype(str).str.strip()
df["YEAR"] = pd.to_datetime(df["YEAR"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4116 entries, 0 to 4115
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SUBDIVISION  4116 non-null   object
 1   YEAR         4116 non-null   datetime64[ns]
 2   JAN          4116 non-null   float64
 3   FEB          4116 non-null   float64
 4   MAR          4116 non-null   float64
 5   APR          4116 non-null   float64
 6   MAY          4116 non-null   float64
 7   JUN          4116 non-null   float64
 8   JUL          4116 non-null   float64
 9   AUG          4116 non-null   float64
 10  SEP          4116 non-null   float64
 11  OCT          4116 non-null   float64
 12  NOV          4116 non-null   float64
 13  DEC          4116 non-null   float64
 14  ANNUAL       4116 non-null   float64
 15  Jan-Feb      4116 non-null   float64
 16  Mar-May      4116 non-null   float64
 17  Jun-Sep      4116 non-null   float64
 18  Oct-Dec      4116 non-null   float64
dtypes: datetime64[ns](1), float64(17), object(1)
memory usage: 611.1+ KB

In [25]:
print(df.head())
print(df.columns)

                 SUBDIVISION       YEAR   JAN    FEB   MAR    APR    MAY  \
0  ANDAMAN & NICOBAR ISLANDS 1901-01-01  49.2   87.1  29.2    2.3  528.8
1  ANDAMAN & NICOBAR ISLANDS 1902-01-01   0.0  159.8  12.2    0.0  446.1
2  ANDAMAN & NICOBAR ISLANDS 1903-01-01  12.7  144.0   0.0    1.0  235.1
3  ANDAMAN & NICOBAR ISLANDS 1904-01-01   9.4   14.7   0.0  202.4  304.5
4  ANDAMAN & NICOBAR ISLANDS 1905-01-01   1.3    0.0   3.3   26.9  279.5

     JUN    JUL    AUG    SEP    OCT    NOV    DEC  ANNUAL  Jan-Feb  Mar-May  \
0  517.5  365.1  481.1  332.6  388.5  558.2   33.6  3373.2    136.3    560.3
1  537.1  228.9  753.7  666.2  197.2  359.0  160.5  3520.7    159.8    458.3
2  479.9  728.4  326.7  339.0  181.2  284.4  225.0  2957.4    156.7    236.1
3  495.1  502.0  160.1  820.4  222.2  308.7   40.1  3079.6     24.1    506.9
4  628.7  368.7  330.5  297.0  260.7   25.4  344.7  2566.7      1.3    309.7

   Jun-Sep  Oct-Dec
0   1696.3    980.3
1   2185.9    716.7
2   1874.0    690.6
3   1977.6    571.0
4   1624.9    630.8
Index(['SUBDIVISION', 'YEAR', 'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL',
       'AUG', 'SEP', 'OCT', 'NOV', 'DEC', 'ANNUAL', 'Jan-Feb', 'Mar-May',
       'Jun-Sep', 'Oct-Dec'],
      dtype='object')

In [33]:
import pandas as pd

# Numerical columns
num_cols = ["YEAR", "JAN", "FEB", "MAR", "APR", "MAY",
            "JUN", "JUL", "AUG", "SEP", "OCT", "NOV",
            "DEC", "ANNUAL", "Jan-Feb", "Mar-May",
            "Jun-Sep", "Oct-Dec"]

# Fill numerical missing values with mean
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

# Fill categorical missing values with mode
df["SUBDIVISION"] = df["SUBDIVISION"].fillna(df["SUBDIVISION"].mode()[0])

# Check missing values
print(df.isnull().sum())

SUBDIVISION    0
YEAR           0
JAN            0
FEB            0
MAR            0
APR            0
MAY            0
JUN            0
JUL            0
AUG            0
SEP            0
OCT            0
NOV            0
DEC            0
ANNUAL         0
Jan-Feb        0
Mar-May        0
Jun-Sep        0
Oct-Dec        0
dtype: int64

In [34]:
print(df.head())
print(df.columns)

                 SUBDIVISION       YEAR   JAN    FEB   MAR    APR    MAY  \
0  andaman & nicobar islands 1901-01-01  49.2   87.1  29.2    2.3  528.8
1  andaman & nicobar islands 1902-01-01   0.0  159.8  12.2    0.0  446.1
2  andaman & nicobar islands 1903-01-01  12.7  144.0   0.0    1.0  235.1
3  andaman & nicobar islands 1904-01-01   9.4   14.7   0.0  202.4  304.5
4  andaman & nicobar islands 1905-01-01   1.3    0.0   3.3   26.9  279.5

     JUN    JUL    AUG    SEP    OCT    NOV    DEC  ANNUAL  Jan-Feb  Mar-May  \
0  517.5  365.1  481.1  332.6  388.5  558.2   33.6  3373.2    136.3    560.3
1  537.1  228.9  753.7  666.2  197.2  359.0  160.5  3520.7    159.8    458.3
2  479.9  728.4  326.7  339.0  181.2  284.4  225.0  2957.4    156.7    236.1
3  495.1  502.0  160.1  820.4  222.2  308.7   40.1  3079.6     24.1    506.9
4  628.7  368.7  330.5  297.0  260.7   25.4  344.7  2566.7      1.3    309.7

   Jun-Sep  Oct-Dec
0   1696.3    980.3
1   2185.9    716.7
2   1874.0    690.6
3   1977.6    571.0
4   1624.9    630.8
Index(['SUBDIVISION', 'YEAR', 'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL',
       'AUG', 'SEP', 'OCT', 'NOV', 'DEC', 'ANNUAL', 'Jan-Feb', 'Mar-May',
       'Jun-Sep', 'Oct-Dec'],
      dtype='object')

In [30]:
df.to_csv("cleaned_rainfall.csv", index=False)

In [31]:
import pandas as pd
from google.colab import files

# Convert to Excel
df.to_excel("cleaned_rainfall.xlsx", index=False)

# Download
files.download("cleaned_rainfall.xlsx")

In [35]:
df.info()
df.isnull().sum()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4116 entries, 0 to 4115
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SUBDIVISION  4116 non-null   object
 1   YEAR         4116 non-null   datetime64[ns]
 2   JAN          4116 non-null   float64
 3   FEB          4116 non-null   float64
 4   MAR          4116 non-null   float64
 5   APR          4116 non-null   float64
 6   MAY          4116 non-null   float64
 7   JUN          4116 non-null   float64
 8   JUL          4116 non-null   float64
 9   AUG          4116 non-null   float64
 10  SEP          4116 non-null   float64
 11  OCT          4116 non-null   float64
 12  NOV          4116 non-null   float64
 13  DEC          4116 non-null   float64
 14  ANNUAL       4116 non-null   float64
 15  Jan-Feb      4116 non-null   float64
 16  Mar-May      4116 non-null   float64
 17  Jun-Sep      4116 non-null   float64
 18  Oct-Dec      4116 non-null   float64
dtypes: datetime64[ns](1), float64(17), object(1)
memory usage: 611.1+ KB

,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
count,4116,4116.000000,4116.000000,4116.000000,4116.000000,4116.000000,4116.000000,4116.000000,4116.000000,4116.000000,4116.000000,4116.000000,4116.000000,4116.000000,4116.000000,4116.000000,4116.000000,4116.000000
mean,1958-03-21 17:50:33.236151616,18.957320,21.805325,27.359197,43.127432,85.745417,230.234444,347.214334,290.263497,197.361922,95.507009,39.866163,18.870580,1411.008900,40.747786,155.901753,1064.724769,154.100487
min,1901-01-01 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.400000,0.000000,0.000000,0.100000,0.000000,0.000000,0.000000,62.300000,0.000000,0.000000,57.400000,0.000000
25%,1930-01-01 00:00:00,0.600000,0.600000,1.000000,3.000000,8.600000,70.475000,175.900000,156.150000,100.600000,14.600000,0.700000,0.100000,806.450000,4.100000,24.200000,574.375000,34.200000
50%,1958-01-01 00:00:00,6.000000,6.700000,7.900000,15.700000,36.700000,138.900000,284.900000,259.500000,174.100000,65.750000,9.700000,3.100000,1125.450000,19.300000,75.200000,882.250000,98.800000
75%,1987-01-01 00:00:00,22.125000,26.800000,31.225000,49.825000,96.825000,304.950000,418.225000,377.725000,265.725000,148.300000,45.825000,17.700000,1635.100000,50.300000,196.900000,1287.550000,212.600000
max,2015-01-01 00:00:00,583.700000,403.500000,605.600000,595.100000,1168.600000,1609.900000,2362.800000,1664.600000,1222.000000,948.300000,648.900000,617.500000,6331.100000,699.500000,1745.800000,4536.900000,1252.500000
std,NaN,33.569044,35.896396,46.925176,67.798192,123.189974,234.568120,269.310313,188.678707,135.309591,99.434452,68.593545,42.318098,900.986632,59.265023,201.096692,706.881054,166.678751

In [38]:
import pandas as pd
import numpy as np

data = {
    "name": ["Amit", "Sara", "John", "Amit", None],
    "age": [20, 21, np.nan, 20, 19],
    "gender": ["Male", "female", "Male", "Male", "FEMALE"],
    "marks": [85, 90, 105, 85, -5],
    "attendance": [90, 85, 80, 90, None],
    "city": ["Mumbai", "Delhi", "mumbai", "Mumbai", "Pune"]
}

df = pd.DataFrame(data)
df

   name   age  gender  marks  attendance    city
0  Amit  20.0    Male     85        90.0  Mumbai
1  Sara  21.0  female     90        85.0   Delhi
2  John   NaN    Male    105        80.0  mumbai
3  Amit  20.0    Male     85        90.0  Mumbai
4  None  19.0  FEMALE     -5         NaN    Pune

In [39]:
# Fill missing values in numerical columns
df["age"] = df["age"].fillna(df["age"].mean())
df["attendance"] = df["attendance"].fillna(df["attendance"].mean())

# Fill missing values in categorical column
df["name"] = df["name"].fillna("Unknown")

# Display dataset
df

      name   age  gender  marks  attendance    city
0     Amit  20.0    Male     85       90.00  Mumbai
1     Sara  21.0  female     90       85.00   Delhi
2     John  20.0    Male    105       80.00  mumbai
3     Amit  20.0    Male     85       90.00  Mumbai
4  Unknown  19.0  FEMALE     -5       86.25    Pune

In [40]:
df["gender"] = df["gender"].str.lower()
df["city"] = df["city"].str.lower()

df

      name   age  gender  marks  attendance    city
0     Amit  20.0    male     85       90.00  mumbai
1     Sara  21.0  female     90       85.00   delhi
2     John  20.0    male    105       80.00  mumbai
3     Amit  20.0    male     85       90.00  mumbai
4  Unknown  19.0  female     -5       86.25    pune

In [41]:
df = df[(df["marks"] >= 0) & (df["marks"] <= 100)]

df

   name   age  gender  marks  attendance    city
0  Amit  20.0    male     85        90.0  mumbai
1  Sara  21.0  female     90        85.0   delhi
3  Amit  20.0    male     85        90.0  mumbai